# Site settings
title:       Blog | michaelzg
email:       ""
author:      Michael Gao
description: "Michael G."
baseurl:     ""
url:         "https://michaelzg.com"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username: 
linkedin_username:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     6
sass:
  compressed: true
highlighter: rouge

gems: [jekyll-paginate]