# Site settings
title: Hmphs and Ah Hahs
email: michaelzgao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Recent environmental engineering graduate from Johns Hopkins
  University. I'm interested in problems within the environment
  and tackling them with computers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mgao.me" # the base hostname & protocol for your site
twitter_username: mchlgao
github_username:  michaelzg

# Build settings
markdown: kramdown
